valmi_postgres:
  target: valmi
  outputs:
    valmi:
      type: postgres
      host: localhost
      user: postgres
      password: changeme
      port: 5432
      dbname: valmi_app
      schema: valmi_scratch_4a98a9e5660f42acbe299d2b949e9807
      threads: 4
config:
    send_anonymous_usage_stats: False
