DEBUG: True
DELETE_METRICS_DB: False
APP_BACKEND: localhost
APP_BACKEND_PORT: 4000
DAGIT_HOST: localhost
DAGIT_PORT: 4002
APP: "valmi"
REPO_NAME: "valmi-repo"
DATABASE_URL: "postgresql://postgres:changeme@localhost:5432/valmi_activation"
DAGTSER_MAX_TRIES: 3
DAGSTER_MIN_RETRY_INTERVAL: 10
DAGSTER_MAX_RETRY_INTERVAL: 120
LOGGER_NAME: "valmi"
ADMIN_USERNAME: "admin-changeme"
ADMIN_EMAIL: "admin-changeme@valmi.io"
ADMIN_PASSWORD: "changeme"

HTTP_REQ_TIMEOUT: 10 #seconds
LOGGING_CONF:
  version: 1
  formatters:
    simple:
      # {}-formatting(std.format), please see https://docs.python.org/3/library/logging.html#logrecord-attributes
      format: "{asctime} {levelname: <8} {threadName: <10.10} {module: >32}::{funcName: <20.20} {message}"
      datefmt: "%m/%d/%Y %I:%M:%S %p"
      style: "{"
  handlers:
    console:
      class: logging.StreamHandler
      level: DEBUG
      formatter: simple
      stream: ext://sys.stdout
  loggers:
    valmi:
      level: DEBUG
      handlers: [console]
    vyper:
      level: INFO
      handlers: [console]
  root:
    level: DEBUG
    handlers: [console]
  disable_existing_loggers: false

## chunk size per destination
CONNECTOR_RUN_CONFIG:
  FACEBOOK_ADS:
    chunk_size: 9500

