version: "3.8"

services:
  valmi-activation:
      image: valmi-activation:latest
      ports:
        - "8000:8000"
      command: uvicorn --reload --host 0.0.0.0 --port 8000 main:app
      volumes:
        - .:/workspace:z
      #depends_on:
      #  - db
      environment:
        DATABASE_URL: "postgresql://postgres:changeme@localhost:5432/docker_valmi"
