version: "3.8"

services:
  valmi-activation:
    image: valmi/valmi-activation:latest
    ports:
      - "8000:8000"
    command: ["uvicorn", "main:app",   "--port", "8000", "--host","0.0.0.0", "--log-level" ,"debug"]

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp:z
      - .:/workspace:z
    #depends_on:
    #  - db
    environment:
      DATABASE_URL: "postgresql://postgres:changeme@localhost:5432/valmi"
