version: "3.8"

services:
  dagit:
    image: valmiio/valmi-dagster:latest
    ports:
      - "4002:4002"

  dagster_daemon:
    image: valmiio/valmi-dagster:latest

  valmi-repo:
    image: valmiio/valmi-repo:latest

  valmi-activation:
    image: valmiio/valmi-activation:latest
    command:
      [
        "uvicorn",
        "main:app",
        "--port",
        "8000",
        "--host",
        "0.0.0.0",
        "--log-level",
        "debug"
      ]
    ports:
      - "8000:8000"

  valmi-app-backend:
    image: valmiio/valmi-app-backend:latest

  valmi-app:
    image: valmiio/valmi-app:latest
