version: "3.8" 

services:
  # This service runs dagit, which loads your user code from the user code container.
  # Since our instance uses the QueuedRunCoordinator, any runs submitted from dagit will be put on
  # a queue and later dequeued and launched by dagster-daemon.
  dagit:
    build:
      context: ./dagster
      dockerfile: Dockerfile_dagster
    container_name: valmi-dagit
    entrypoint:
      - dagit
      - -h
      - "0.0.0.0"
      - -p
      - "3000"
      - -w
      - workspace.yaml
    expose:
      - "3000"
    ports:
      - "4002:3000"
    environment:
      DAGSTER_POSTGRES_USER: "postgres"
      DAGSTER_POSTGRES_PASSWORD: "changeme"
      DAGSTER_POSTGRES_DB: "valmi_dagster"
    volumes: # Make docker client accessible so we can terminate containers from dagit
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/io_manager_storage:/tmp/io_manager_storage
      - /tmp/shared_dir:/tmp/shared_dir

    networks:
      - valmi-network
    depends_on:
      - valmi-db
      - valmi-repo
      
  # This service runs the dagster-daemon process, which is responsible for taking runs
  # off of the queue and launching them, as well as creating runs from schedules or sensors.
  dagster_daemon:
    build:
      context: ./dagster
      dockerfile: Dockerfile_dagster
    entrypoint:
      - dagster-daemon
      - run
    container_name: valmi-dagster-daemon
    restart: on-failure
    environment:
      DAGSTER_POSTGRES_USER: "postgres"
      DAGSTER_POSTGRES_PASSWORD: "changeme"
      DAGSTER_POSTGRES_DB: "valmi_dagster"
    volumes: # Make docker client accessible so we can launch containers using host docker
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/io_manager_storage:/tmp/io_manager_storage
      - /tmp/shared_dir:/tmp/shared_dir
    networks:
      - valmi-network
    depends_on:
      - valmi-db
      - valmi-repo


###############################################################################################
  # This service runs the postgres DB used by dagster for run storage, schedule storage,
  # and event log storage.
  valmi-db:
    image: postgres:13.2
    container_name: valmi-db
    command: ["postgres", "-c", "log_statement=all"]
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "changeme"
      POSTGRES_DB: "valmi_dagster"
      PGDATA: /data/postgres
    restart: unless-stopped
    networks:
      - valmi-network

  # This service runs the gRPC server that loads your user code, in both dagit
  # and dagster-daemon. By setting DAGSTER_CURRENT_IMAGE to its own image, we tell the
  # run launcher to use this same image when launching runs in a new container as well.
  # Multiple containers like this can be deployed separately - each just needs to run on
  # its own port, and have its own entry in the workspace.yaml file that's loaded by dagit.
  valmi-repo:
    build:
      context: ./dagster
      dockerfile: Dockerfile_user_code
      labels:
        - "io.valmi.name=valmi-repo"
    container_name: valmi-repo
    image: valmi-repo
    restart: always
    environment:
      DAGSTER_POSTGRES_USER: "postgres"
      DAGSTER_POSTGRES_PASSWORD: "changeme"
      DAGSTER_POSTGRES_DB: "valmi_dagster"
      DAGSTER_CURRENT_IMAGE: "valmi-repo"
    networks:
      - valmi-network
    volumes: # Make docker client accessible so we can terminate containers from dagit
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/shared_dir:/tmp/shared_dir:z

  valmi-activation:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    command: ["uvicorn", "main:app",   "--port", "8000", "--host", "0.0.0.0",  "--log-level" ,"debug","--reload"]
    container_name: valmi-activation
    restart: on-failure

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/shared_dir:/tmp/shared_dir:z
      - .:/workspace:z
    networks:
      - valmi-network
    depends_on:
      - valmi-db
      - dagit
    environment:
      DATABASE_URL: "postgresql://postgres:changeme@valmi-db:5432/valmi_activation"
      APP_BACKEND: "host.docker.internal"
      DAGIT_HOST: "dagit"
      DAGIT_PORT: 3000


  valmi-app-backend:
    env_file:
      - ./valmi-app-backend/.env
    ports:
      - "4000:4000"
    build:
      context: ./valmi-app-backend
      dockerfile: Dockerfile
    container_name: valmi-app-backend
    restart: on-failure
    volumes:
      - ./valmi-app-backend:/workspace:z
    networks:
      - valmi-network
    depends_on:
      - valmi-db
    environment:
      DATABASE_URL: "postgresql://postgres:changeme@valmi-db:5432/valmi_app"
      ACTIVATION_SERVER: "http://valmi-activation:8000"



volumes:
    postgres:

networks:
  valmi-network:
    driver: bridge
    name: valmi-network 

