version: "3.8"

services:
  dagit:
    image: valmiio/valmi-dagster:latest

  dagster_daemon:
    image: valmiio/valmi-dagster:latest

  valmi-db:
    command: ["postgres"]

  valmi-repo:
    image: valmiio/valmi-repo:latest

  valmi-activation:
    image: valmiio/valmi-activation:latest
    command:
      [
        "uvicorn",
        "main:app",
        "--port",
        "8000",
        "--host",
        "0.0.0.0",
        "--log-level",
        "debug",
        "--workers",
        "1"
      ]

  valmi-app-backend:
    image: valmiio/valmi-app-backend:latest

  valmi-app:
    image: valmiio/valmi-app:latest
    ports:
      - "3000:3000"
    container_name: valmi-app
    restart: on-failure
    networks:
      - valmi-network
    depends_on:
      - valmi-db
      - valmi-app-backend
    volumes:
      - ./valmi-app/.env:/app/.env
