version: 2

sources:
  - name: aliased_source
    database: dvdrental
    schema: public
    tables:
      - name: customer 
  - name: scratch
    database: dvdrental
    schema: valmi_scratch_computed_
    tables:
      - name: finalized_snapshot 
      - name: transit_snapshot 
      - name: stg_snapshot
      - name: cleanup_snapshot
      - name: ignored_snapshot 

models:
  - name: stg_snapshot
    description: This table has basic information about a customer, as well as some derived facts based on a customer's orders
