name: Valmi connector docker build
on:
  push:
    tags:
      - 'valmi-connector/*/*.*.*'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: 
          submodules: recursive
      - name: Parse Connector Info
        id: vars
        run: |
          tag=${GITHUB_REF#refs/*/}
          connector_tag=${tag#valmi-connector/}
          echo "connector_name=${connector_tag%/*}" >> $GITHUB_OUTPUT
          echo "version=${connector_tag#*/}" >> $GITHUB_OUTPUT
      - name: Setup Docker BuildX
        run: make setup-buildx
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Connector Docker Image
        env:
          connector_name: ${{steps.vars.outputs.connector_name}}
          version: ${{steps.vars.outputs.version}}
        run: make build-and-push-connector
