name: Valmi repo docker build
on:
  push:
    tags:
      - 'valmi-repo/*.*.*'
jobs:
  release:
    runs-on: ubuntu-latest
    name: ${{github.ref_name}}
    steps:
      - uses: actions/checkout@v2
      - name: Parse Connector Info
        id: vars
        run: |
          tag=${GITHUB_REF#refs/*/}
          echo "version=${tag#valmi-repo/}" >> $GITHUB_OUTPUT
      - name: Setup Docker BuildX
        run: make setup-buildx
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build valmi-repo Docker Image
        env:
          valmi_repo_version: ${{steps.vars.outputs.version}}
        run: make build-and-push-valmi-repo
